events {
    worker_connections 1024; # Número de conexiones por proceso
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
    # Escucha en el puerto 80 (HTTP) y redirige todo a HTTPS
    listen 86;
    server_name localhost 192.168.0.101; # O tu dominio si tienes uno
    return 301 https://$host$request_uri;
}

server {
    # Escucha en el puerto 443 (HTTPS)
    listen 8002 ssl;
    server_name localhost 192.168.0.101; # O tu dominio

    # Rutas a los certificados que generaste
    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    # Configuraciones de SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';

    location / {
        # Redirige el tráfico a tu aplicación Node.js
        proxy_pass http://app:3000; # 'app' es el nombre del servicio en docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
}
